[WIP]キャンセル機能を追加
Hiroshiba/voicevox_engine pull request #166
Opened 2021-10-30 15:33 UTC by takana-v

## 内容
音声合成を途中でキャンセルすることができる、`/cancellable_synthesis`を追加します。

起動時にプロセスを2つ作成し、使用可能なプロセスのリストに情報を格納します。
（初回の音声合成で初期化の時間を短縮するため）
`/cancellable_synthesis`が呼ばれた際、使えるプロセスがある場合、リストから取り出してそのプロセスで音声合成します。
無い場合は新しくプロセスを作成します。（この場合は通常より時間が掛かります）

非同期で1秒ごとに通信状況を監視しています。
通信が切断されていてサブプロセスが動いている場合はサブプロセスをキルします。

合成が完了したら、結果を返し、使用していたプロセスを使用可能プロセスリストに格納します。

## 関連 Issue
close #64 
- #64 

## スクリーンショット・動画など
一つ目の山が通常合成です。
二つ目の山が途中でキャンセルしたものです。
キャンセル後に新しくプロセスを起動し、コアを初期化しているのでCPU使用率がすぐには落ちません。

![image](https://user-images.githubusercontent.com/44311840/139539063-8fc53e5b-ad14-4f0f-af5d-e08a67d9770e.png)

## 既知の問題
通常の音声合成中は通信の監視が止まります。

## その他
`multiprocessing`を使用していますが、このモジュールはOSによって挙動が異なります。
また、バイナリ化すると問題が発生することもあります。
windowsでは動作確認できましたが、その他の環境では動作確認できていないのでWIPとしています。

2021-10-31 13:03 UTC, Hiroshiba requested changes
良いですね！！

やはりキャンセルした後の再起動はやはり結構時間がかかりますか？

たしかにmultiprocess周りはOS依存で挙動が変わってくるイメージがあるので、Linuxで動くかは確認しておくと良いなと思いました！

2021-10-31 13:03 UTC, Hiroshiba commented on run.py
> +    procs = []
この辺りクラス化してまとめると、変数をまとめられたり機能追加がやりやすいかもです。

2021-11-01 13:01 UTC, takana-v commented on run.py
> +        summary="音声合成する",
https://github.com/Hiroshiba/voicevox_engine/pull/166/commits/9cf3cce74187599d5b93c029692b9b177e6572d9 にて明示しました。

2021-11-01 13:02 UTC, takana-v commented on run.py
> +def wrap_synthesis(args, con):
https://github.com/Hiroshiba/voicevox_engine/pull/166/commits/0bcc93ee88434331f204854b9e7a46829314c1b7 にて型ヒントを追加しました。

2021-11-01 13:02 UTC, takana-v commented on run.py
> +    procs = []
https://github.com/Hiroshiba/voicevox_engine/pull/166/commits/1c753f72b7ceb1ae8bface2041e87a756b54f6c8 にて関連機能をクラス化してまとめました。

2021-11-01 13:19 UTC, takana-v commented
取りあえず指摘のあった部分を変更しました。
Linux版は未テストです。
コアの初期化には3.5秒ほど（自環境、CPU）かかりました。
キャンセルしない場合の速度は、通常より0.1秒ほど遅くなる感じです。(3回しか測っていませんが)
```
synthesis
5.86979079246521
5.783113718032837
5.701512098312378
------
cancellable_synthesis
5.9672369956970215
5.984399318695068
5.8871166706085205
```
（テスト一切書いていないのに何でカバレッジのテスト通っているんでしょうか...）

2021-11-01 19:28 UTC, Hiroshiba requested changes
全体の構想がわかってきました！
どういう通信になっているかちょっとこんがらがったので色々質問させてください・・・！

2021-11-01 19:28 UTC, Hiroshiba commented on run.py
> +class ProcessManager:
`ProcessManager`クラスに切り出せたので、そもそもどういう設計で作られているかの説明をクラスのコメントに書くとわかりやすいのかなと思いました。

2021-11-01 19:28 UTC, Hiroshiba commented on run.py
> +        ] = []
`connections`に`Connection`の型ではないなにかが入っていたり、`procs`の中に`Connection`があったりと、データ構造が入り組んでしまっているように感じました。
プロセス間通信周りの変数は、どっちのprocessなのか、何と何に対するconnectionなのかがややこしくなる印象があります。
何が保存されることを想定しているかわかる変数名にしたり、説明があると良いのかも・・・？

2021-11-01 19:28 UTC, Hiroshiba commented on run.py
> +            ret_proc.start()
この処理が３箇所くらいにありそうなのでメソッドにしても良さそう

2021-11-01 19:28 UTC, Hiroshiba commented on run.py
> +            if len(self.procs) <= 5:
ここの5という数値や、ちょっと下にある`len(self.procs) <= 4`など、条件の意味を知りたいです。

2021-11-01 19:28 UTC, Hiroshiba commented on run.py
> +        return FileResponse(f_name, media_type="audio/wav")
multiprocess周りの実装（conやproc）は完全に隠蔽した状態で使えるのが理想的だと思います。
これらもまとめてCancellabelSynthesisEngineにしてしまうと良いかも・・・？

2021-11-01 19:28 UTC, Hiroshiba commented on run.py
> +    )
あ、そうか、別プロセスだからエンジンがもう１ついりますね･･･。
GPUメモリの消費量が上がるのでできれば１つで済むようにしたいところですが、一本化する（/synthesisをそもそも/cancellable_synthesis置き換える）のはいろんな実機で実証できてからかなと感じました。

cancel機能は実験的機能という立て付けにして、enableにしたらそのAPIが利用できるようにするというのはどうでしょう。

2021-11-02 10:13 UTC, takana-v commented
指摘のあった部分を変更しました。
docstringを追加したので多少は分かりやすくなっていると思います。
名前をCancellableEngineクラスに変更し、CancellableEngine.synthesisで音声合成できるように変更しています。

2021-11-02 18:20 UTC, Hiroshiba requested changes
ロジックがちょっとわかったのでまた色々コメントを書きました！！

2021-11-02 18:20 UTC, Hiroshiba commented on run.py
> +            async with lock:
同じlockインスタンスを使っている場所がないので、たぶんlockしてもしなくても挙動は全く一緒なのかなと思います。
やりたいことはどんな感じでしょう？👀

2021-11-02 18:20 UTC, Hiroshiba commented on run.py
> +def wrap_synthesis(
本当はこの関数もcancelable engineと一緒にrun.pyから外せると綺麗なのですが、難しそうですね・・・

2021-11-02 18:20 UTC, Hiroshiba commented on run.py
> +        cancellable_engine = CancellableEngine()
if内に書くと`cancellable_engine`変数がglobalに存在する場合としない場合が出てきそうです。
`cancellable_engine`変数をoptionalにしておいて、デフォルトはNoneにすると良いかもです。

2021-11-02 19:35 UTC, takana-v commented
一旦ファイルを切り出しました。
それに伴い、make_synthesis_engine関数がsynthesis_engine.pyの中に移動しています。
この方針で進めて大丈夫かどうか確認していただければと思います。

2021-11-03 03:54 UTC, Hiroshiba commented
良いと思います！！

少し手間ですが、make_synthesis_engineを移動させるだけのプルリクエストを頂けると嬉しいです。
（いろんなレビューをしていて何度か経験があったのですが、移動やリファクタリングが含まれるコードのレビュー中に別の修正が入った場合、コンフリクト解消でデグレっていても気づけないので･･･）

2021-11-09 14:19 UTC, takana-v commented
ご指摘の点修正しました。
一部変数名を変更しています。

以下は新しいバージョンの仕様です。
- `--enable_cancellable_synthesis True`が入っている場合に有効化
- `--init_processes`の数だけ起動時にサブプロセスを立ち上げる
- `--init_processes`の数よりサブプロセスが増えることは無い

synthesis時に`procs_and_cons`からプロセスを取得し、終了時（synthesisまたはcatch_disconnection）に呼ばれる`finalize_con`で`procs_and_cons`にプロセスを追加します。

2021-11-10 18:54 UTC, Hiroshiba requested changes
すごく読みやすくなったと感じました！！
もしよければこちらのAPIの使い方をREADMEに書くのもお願いしても良いでしょうか。
（デバッグしやすいのと、エディタ側やサードパーティ開発者にかなり伝わりやすくなるためです）

2021-11-10 18:54 UTC, Hiroshiba commented on voicevox_engine/cancellable_engine.py
> +def synthesis_subprocess(
subprocessでsynthesisする関数と勘違いするかもなので、`start_synthesis_subprocess`辺りにすると更にわかりやすいかもと思いました！

2021-11-11 13:46 UTC, takana-v commented
readme追加等行いました。
（文言は編集していただいて構いません）

2021-11-11 15:29 UTC, Hiroshiba approved these changes
LGTM！！
今は初期化に時間がかかるのでキャンセルしないほうが良いかもしれませんが、onnx化などが進んで初期化が速くなったらかなり役に立つのではないかと思います・・・！

2021-11-11 15:30 UTC, Hiroshiba commented on README.md
> +このAPIは実験的機能であり、エンジン起動時に引数で`--enable_cancellable_synthesis True`を指定しないと有効化されません。
ちょっとargparse周りでテクニックが有るので修正しちゃいます

```suggestion
このAPIは実験的機能であり、エンジン起動時に引数で`--enable_cancellable_synthesis`を指定しないと有効化されません。  
```

2021-11-11 15:30 UTC, Hiroshiba commented on run.py
> +    parser.add_argument("--enable_cancellable_synthesis", type=bool, default=False)
```suggestion
    parser.add_argument("--enable_cancellable_synthesis", action="store_true")
```

2021-11-11 15:34 UTC, merged