/charactor_infoを追加
Hiroshiba/voicevox_engine pull request #175
Opened 2021-11-03 11:36 UTC by takana-v

## 内容
 CharactorInfoが必要な情報（立ち絵など）を提供する`/charactor_info`を追加します。

## 関連 Issue
close #169 
- #169 
- https://github.com/Hiroshiba/voicevox/issues/433

## スクリーンショット・動画など

## その他
バイナリ化しても動くか、そもそもビルド周りのコードが合っているかが不明なためDraftです。
自環境ではnuitkaがよく分からないエラーを吐いてビルドが通らない（今のmainブランチでも）なので誰か検証していただける方を募集しています。
また、`build.yml`や`Dockerfile`も未検証です。
詳しい方がいらっしゃいましたら確認して頂けると幸いです。

2021-11-03 11:39 UTC, Hiroshiba commented
とりあえず気になった点だけ…characterがタイポしてるかもです！

2021-11-03 11:41 UTC, Hiroshiba commented
github actionsによるビルドも通らなそうでしょうか？
github上で適当にreleaseを作れば（かなりの時間がかかりますが）試せると思います！

2021-11-03 16:03 UTC, takana-v commented
ビルドのテストを行いました。
windowsとmacは通っています。
（windows-cpuで実機動作確認済）
https://github.com/takana-v/voicevox_engine/runs/4092236375?check_suite_focus=true
dockerfileを使うlinuxのビルドが失敗しています。

2021-11-03 16:10 UTC, takana-v commented
修正を入れたので現在確認中です。
https://github.com/takana-v/voicevox_engine/actions/runs/1417601561

2021-11-03 22:18 UTC, Hiroshiba requested changes
良さそうです！！

今更なのですが、エンジン側にはcharacterという概念がなく、話者（speaker）で統一していることに気づきました。
いつかエディタ側と合わせたほうが良さそうですが、ここはAPIなので同じようにspeakerで統一しておくというのはどうでしょう。
（バージョン１になるときとかにまた再考するのが良いのかなと思いました。）

2021-11-03 22:18 UTC, Hiroshiba commented on .github/workflows/build.yml
> +            --include-data-dir=../characters_info=./characters_info \
エディターの方は`character_infos`なのでちょっとややこしそうです。
そもそもキャラが１人の可能性もあるので、特に複数形の`s`は付けずにcharacter_infoディレクトリにするのはどうでしょう？

2021-11-03 22:18 UTC, Hiroshiba commented on run.py
> +                policy = f.read()
ちょっとしたテクニックですが、
```python
Path(f"characters_info/{character_uuid}/policy.md").read_text("utf-8")
```
とすると１行で書けたりします。

2021-11-03 22:18 UTC, Hiroshiba commented on run.py
> +                portrait = base64.b64encode(f.read()).decode("utf-8")
こっちの場合は
```python
portrait = base64.b64encode(Path(f"characters_info/{character_uuid}/portrait.png").read_bytes()).decode("utf-8")
```
とかですが、流石に読みにくいですね・・・。

2021-11-03 22:18 UTC, Hiroshiba commented on run.py
> +                    icons[file_name] = base64.b64encode(f.read()).decode("utf-8")
結構現れるので関数化しても良さそうに思いました。

2021-11-03 22:18 UTC, Hiroshiba commented on run.py
> +                    )
合ってるかちょっと自信ないですが、こう書けるかもです
```python
for p in Path(f"characters_info/{character_uuid}/voice_samples").glob("*"):
  voice_samples[p.stem] = base64.b64encode(p.read_bytes()).decode("utf-8")
```

2021-11-03 22:18 UTC, Hiroshiba commented on voicevox_engine/model.py
> +    フロントのCharacterInfoが必要な情報
サードパーティでも使われることを想定できそうなので、「話者の追加情報」とかでどうでしょう。

2021-11-04 00:38 UTC, takana-v commented
確かにpathlib使った方がきれいに書けますね。
character_infoからspeaker_infoに修正しました。

2021-11-04 16:23 UTC, Hiroshiba approved these changes
LGTM！！
Nuitkaビルドをしても問題ないことも確認して頂きありがとうございます・・・！

もしよかったらREADMEに追加の話者情報を取得する方法を書くのはどうでしょう？
（base64エンコード周りとかをちゃんとデコードするのが、なれていないと結構難しそうなので）
情報をcurlで取得し、icon.pngのbase64文字列をsedとかで獲得した後、エンコードしてicon.pngとしてバイナリをファイル保存するサンプルがあれば想像しやすいのかなと思いました！

2021-11-04 16:23 UTC, merged