/speaker_infoの返り値を変更
Hiroshiba/voicevox_engine pull request #183
Opened 2021-11-07 09:47 UTC by takana-v

## 内容
題の通り

## 関連 Issue
- https://github.com/Hiroshiba/voicevox/pull/450

2021-11-07 18:40 UTC, Hiroshiba requested changes
実装感謝です！！
気になったところだけコメントしてみました！

2021-11-07 18:40 UTC, Hiroshiba commented on run.py
> +        for i in range(len(metas)):
一時的っぽい変数`i`を後から使うと混乱しやすいかもです。
ほしいのは`metas[i]`なのでそれを変数に代入すればわかりやすいかも。

2021-11-07 18:40 UTC, Hiroshiba commented on voicevox_engine/dev/core/mock.py
> +                    {"name": "dummy1(style3)", "id": 6},
あ、細かいのですが、styleのnameはspeakerのname無しのが使い勝手が良いかもです。
1つ目の`{"name": "dummy1", "id": 0},`のnameが空欄になりますが、エディタ側に合わせてnameキー無しでも良いのかなと思いました。

2021-11-08 11:52 UTC, takana-v commented on run.py
> +        for i in range(len(metas)):
`i`を使わないように変更しました。

2021-11-08 11:53 UTC, takana-v commented on voicevox_engine/dev/core/mock.py
> +                    {"name": "dummy1(style3)", "id": 6},
speakerのname無しに変更しました。
実際のcoreの情報を見てみると全て名前が入っていたので、それに合わせています。
（`style0`、`style1`…のようにしています）

2021-11-08 13:42 UTC, Hiroshiba approved these changes
LGTM！！　変更ありがとうございます！！

2021-11-08 13:42 UTC, merged