リファクタリング: connect_wavesの処理をモジュール化・テストを追加
Hiroshiba/voicevox_engine pull request #197
Opened 2021-11-22 21:12 UTC by aoirint

## 内容

`run.py`の`decode_base64_waves`関数と、その戻り値のndarray配列を結合する処理を`connect_base64_waves`としてモジュール化します。

また、`connect_base64_waves`のテストを追加します。

## 関連 Issue

- #119 
- #16

2021-11-23 09:26 UTC, Hiroshiba requested changes
リファクタリング、とても助かります！！

utilはたぶんutilityの略語で、他のファイルと揃えてutilityにしておくと統一感が有るのかなと思いました。
（細かいですが、意識して統一したほうが良いのかなと思ったので・・・。）

2021-11-23 09:40 UTC, aoirint commented
なるほど、utilityにしてみました！

2021-11-23 10:01 UTC, Hiroshiba requested changes
Request changesにしていますが、そのままマージしても大丈夫だと思います。
言って頂ければそのままマージします！

2021-11-23 10:01 UTC, Hiroshiba commented on test/test_connect_base64_waves.py
> +    x = np.linspace(0, seconds, int(seconds * samplerate), endpoint=False)
たしかデフォルトでfloat64になって、waveはfloat32なので、そこが誤差になっているかもです。
.astype(np.float32)とかすると更に近くなるかも・・・？

2021-11-23 10:38 UTC, aoirint commented on test/test_connect_base64_waves.py
> +    x = np.linspace(0, seconds, int(seconds * samplerate), endpoint=False)
waveファイルに書き出すときに、PCM_16（unsigned int 16bit）で書き出す設定になっていたことが誤差の原因のようでした。

numpy配列側ではfloat32に固定して、soundfileライブラリ側ではfloat32を表すFLOATを指定することで、誤差をなくすことができたので、等価チェックのコメントアウトを外しました。

- FLOATの定義: https://github.com/bastibe/python-soundfile/blob/1bd1529d92382067cb57eb906216a4db2a2d5ec0/soundfile.py#L72

2021-11-23 10:40 UTC, aoirint commented on test/test_connect_base64_waves.py
> +        # self.assertTrue((wave_x2_ref == wave_x2).all())
float32に固定して扱っている限り誤差は出ないと考えたいですが、許容範囲を設定した方がよさそうであれば、修正します！

2021-11-25 23:13 UTC, Hiroshiba approved these changes
LGTM！！
subtypeというのがあるのは知りませんでした！

2021-11-25 23:13 UTC, merged